version: '3'
services:
  app:
    build: .
    #dockerfile: Dockerfie
#      context: .
#      dockerfile: ./node_modules/vail/runtimes/npm/Dockerfile
#      args:
#        VAIL_NODE_VERSION: 20
#    command: npm run dev -- --host 0.0.0.0
    ports:
      - '5173:5173'
    volumes:
      - .:/app
      - /app/node_modules
#networks:
#  vail:
#    driver: bridge
